release: git lfs install && git lfs pull
build: cd backend && make
start: cd backend && ./bin/llama-server --port $PORT --model /app/models/Llama-3.2-3B-Instruct-Q4_K_M.gguf --threads 8 --host 0.0.0.0
